void Right_Turn_Roomba();
void Left_Turn_Roomba();
void Bump_Square_Up();
void Insult();
void Compliment();
void Button_Square_Up();
void Half_Left_Turn_Roomba();
void Half_Right_Turn_Roomba();
void line_follow();
